/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bonitoprint.telas;

import br.com.bonitoprint.controller.FornecedorController;
import br.com.bonitoprint.entidades.Fornecedor;
import br.com.bonitoprint.execao.CampoObrigatorioException;
import br.com.bonitoprint.execao.ErroInternoException;
import br.com.bonitoprint.execao.UsuarioExistenteException;
import javax.swing.JOptionPane;

/**
 *
 * @author Vinicius
 */
public class TelaCadastroFornecedor extends javax.swing.JFrame {
        private TelaPrincipal telaanterior;
    /**
     * Creates new form TelaCadastroFornecedor
     */
    private TelaCadastroFornecedor() {
        initComponents();
    }
     public TelaCadastroFornecedor(TelaPrincipal telaanterior){
        this();
        this.telaanterior=telaanterior;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Estado = new javax.swing.JLabel();
        ClienteBairro = new javax.swing.JLabel();
        ClienteNome = new javax.swing.JLabel();
        CampoFornecedorBairro = new javax.swing.JTextField();
        CampoFornecedorNome = new javax.swing.JTextField();
        Cidade = new javax.swing.JLabel();
        ClienteCpf = new javax.swing.JLabel();
        CampoFornecedorCidade = new javax.swing.JTextField();
        CampoFornecedorCpf = new javax.swing.JTextField();
        BotaoFornecedorCliente = new javax.swing.JButton();
        ClienteEmail = new javax.swing.JLabel();
        BotaoLimparFornecedor = new javax.swing.JButton();
        CampoFornecedorEmail = new javax.swing.JTextField();
        ClienteRua = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        CampoFornecedorRua = new javax.swing.JTextField();
        CampoFornecedorNumero = new javax.swing.JTextField();
        ClienteComplemento = new javax.swing.JLabel();
        CampoFornecedorEstado = new javax.swing.JTextField();
        CampoFornecedorComplemento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CampoTel1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CampoTel2 = new javax.swing.JTextField();
        obrigatorio1 = new javax.swing.JLabel();
        obrigatorio2 = new javax.swing.JLabel();
        obrigatorio3 = new javax.swing.JLabel();
        obrigatorio5 = new javax.swing.JLabel();
        obrigatorio4 = new javax.swing.JLabel();
        obrigatorio6 = new javax.swing.JLabel();
        obrigatorio7 = new javax.swing.JLabel();
        obrigatorio8 = new javax.swing.JLabel();
        obrigatorio9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Administrador");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        Estado.setText("Estado");

        ClienteBairro.setText("Bairro");

        ClienteNome.setText("Nome");

        Cidade.setText("Cidade");

        ClienteCpf.setText("Cpf");

        BotaoFornecedorCliente.setText("Salvar");
        BotaoFornecedorCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoFornecedorClienteActionPerformed(evt);
            }
        });

        ClienteEmail.setText("Email");

        BotaoLimparFornecedor.setText("Limpar");
        BotaoLimparFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLimparFornecedorActionPerformed(evt);
            }
        });

        ClienteRua.setText("Rua");

        jLabel1.setText("nº");

        ClienteComplemento.setText("Complemento");

        jLabel2.setText("Tel1");

        jLabel3.setText("Tel 2");

        CampoTel2.setToolTipText("");

        obrigatorio1.setText("*");

        obrigatorio2.setText("*");

        obrigatorio3.setText("*");

        obrigatorio5.setText("*");

        obrigatorio4.setText("*");

        obrigatorio6.setText("*");

        obrigatorio7.setText("*");

        obrigatorio8.setText("*");

        obrigatorio9.setText("*");

        jLabel4.setText("*Campos Obrigatorios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ClienteNome, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ClienteRua, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(ClienteEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ClienteCpf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(CampoFornecedorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(obrigatorio3))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(CampoFornecedorRua, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(obrigatorio4)
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(CampoFornecedorNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(CampoFornecedorNome, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(obrigatorio1))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(CampoFornecedorCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(obrigatorio2))))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(ClienteComplemento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoFornecedorComplemento))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ClienteBairro)
                                    .addComponent(Cidade)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(Estado))))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CampoFornecedorBairro)
                            .addComponent(CampoFornecedorCidade)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CampoTel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(obrigatorio9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CampoTel2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 12, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(CampoFornecedorEstado))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(BotaoFornecedorCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotaoLimparFornecedor))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(obrigatorio8)))
                        .addGap(31, 31, 31)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(obrigatorio5)
                    .addComponent(obrigatorio6)
                    .addComponent(obrigatorio7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClienteNome, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoFornecedorNome, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(obrigatorio1))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClienteCpf)
                    .addComponent(CampoFornecedorCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(obrigatorio2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClienteEmail)
                    .addComponent(CampoFornecedorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(obrigatorio3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClienteRua)
                    .addComponent(CampoFornecedorRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(CampoFornecedorNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(obrigatorio5)
                    .addComponent(obrigatorio4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClienteComplemento)
                    .addComponent(CampoFornecedorComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClienteBairro)
                    .addComponent(CampoFornecedorBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(obrigatorio6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cidade)
                    .addComponent(CampoFornecedorCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(obrigatorio7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoFornecedorEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Estado)
                    .addComponent(obrigatorio8))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CampoTel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(CampoTel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(obrigatorio9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoFornecedorCliente)
                    .addComponent(BotaoLimparFornecedor)
                    .addComponent(jLabel4))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoFornecedorClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoFornecedorClienteActionPerformed
        // TODO add your handling code here:
        String nome = CampoFornecedorNome.getText();
        String email = CampoFornecedorEmail.getText();
        String cpf = CampoFornecedorCpf.getText();
        String rua = CampoFornecedorRua.getText();
        String complemento = CampoFornecedorComplemento.getText();
        String bairro = CampoFornecedorBairro.getText();
        String cidade = CampoFornecedorCidade.getText();
        String estado = CampoFornecedorEstado.getText();
        String tel1= CampoTel1.getText();
        String tel2 = CampoTel2.getText();
        String num = CampoFornecedorNumero.getText();
        if(num.length()<=0){
           JOptionPane.showMessageDialog(rootPane,"Campo Obrigatorio", "ERRO", JOptionPane.ERROR_MESSAGE);
        }else{
          int numero = Integer.parseInt(CampoFornecedorNumero.getText()); 
         Fornecedor f = new Fornecedor(tel1,tel2,nome,email,cpf,rua,numero,complemento,bairro,cidade,estado);
         FornecedorController fc = new FornecedorController();
        try{
            fc.adicionar(f);
            JOptionPane.showMessageDialog(rootPane,"Fornecedor Cadastrado com Sucesso", "Cadastro de Usuario", JOptionPane.INFORMATION_MESSAGE);
            CampoFornecedorNome.setText("");
            CampoFornecedorEmail.setText("");
            CampoFornecedorCpf.setText("");
            CampoFornecedorRua.setText("");
            CampoFornecedorComplemento.setText("");
            CampoFornecedorBairro.setText("");
            CampoFornecedorCidade.setText("");
            CampoFornecedorEstado.setText("");
            CampoFornecedorNumero.setText("");
            CampoTel1.setText("");
            CampoTel2.setText("");
        }catch(ErroInternoException erro ){
             JOptionPane.showMessageDialog(rootPane,erro.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }catch(UsuarioExistenteException ex){
             JOptionPane.showMessageDialog(rootPane,ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }catch(CampoObrigatorioException ce){
             JOptionPane.showMessageDialog(rootPane,ce.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);

        }
        
      }  
      
    }//GEN-LAST:event_BotaoFornecedorClienteActionPerformed

    private void BotaoLimparFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoLimparFornecedorActionPerformed
        // TODO add your handling code here:

        CampoFornecedorNome.setText("");
        CampoFornecedorEmail.setText("");
        CampoFornecedorCpf.setText("");
        CampoFornecedorRua.setText("");
        CampoFornecedorComplemento.setText("");
        CampoFornecedorBairro.setText("");
        CampoFornecedorCidade.setText("");
        CampoFornecedorEstado.setText("");
        CampoFornecedorNumero.setText("");
        CampoTel1.setText("");
        CampoTel2.setText("");
        
    }//GEN-LAST:event_BotaoLimparFornecedorActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
       telaanterior.setEnabled(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoFornecedorCliente;
    private javax.swing.JButton BotaoLimparFornecedor;
    private javax.swing.JTextField CampoFornecedorBairro;
    private javax.swing.JTextField CampoFornecedorCidade;
    private javax.swing.JTextField CampoFornecedorComplemento;
    private javax.swing.JTextField CampoFornecedorCpf;
    private javax.swing.JTextField CampoFornecedorEmail;
    private javax.swing.JTextField CampoFornecedorEstado;
    private javax.swing.JTextField CampoFornecedorNome;
    private javax.swing.JTextField CampoFornecedorNumero;
    private javax.swing.JTextField CampoFornecedorRua;
    private javax.swing.JTextField CampoTel1;
    private javax.swing.JTextField CampoTel2;
    private javax.swing.JLabel Cidade;
    private javax.swing.JLabel ClienteBairro;
    private javax.swing.JLabel ClienteComplemento;
    private javax.swing.JLabel ClienteCpf;
    private javax.swing.JLabel ClienteEmail;
    private javax.swing.JLabel ClienteNome;
    private javax.swing.JLabel ClienteRua;
    private javax.swing.JLabel Estado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel obrigatorio1;
    private javax.swing.JLabel obrigatorio2;
    private javax.swing.JLabel obrigatorio3;
    private javax.swing.JLabel obrigatorio4;
    private javax.swing.JLabel obrigatorio5;
    private javax.swing.JLabel obrigatorio6;
    private javax.swing.JLabel obrigatorio7;
    private javax.swing.JLabel obrigatorio8;
    private javax.swing.JLabel obrigatorio9;
    // End of variables declaration//GEN-END:variables
}
