/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bonitoprint.telas;

import br.com.bonitoprint.controller.ProdutoController;
import br.com.bonitoprint.entidades.Produto;
import br.com.bonitoprint.execao.ErroInternoException;
import br.com.bonitoprint.execao.UsuarioInexistenteException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Vinicius
 */
public class TelaEstoque extends javax.swing.JFrame {
     
    private TelaPrincipal telaanterior;
    /**
     * Creates new form TelaEstoque
     */
    private TelaEstoque() {
        initComponents();
    }
    public TelaEstoque(TelaPrincipal telaanterior){
        this();
        this.telaanterior = telaanterior;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        NomedoProduto = new javax.swing.JLabel();
        CampoPesqNome = new javax.swing.JTextField();
        BotaoPesquisar = new javax.swing.JButton();
        ComboProduto = new javax.swing.JComboBox();
        Produto = new javax.swing.JLabel();
        BotaoSelecionar = new javax.swing.JButton();
        CampoNome = new javax.swing.JTextField();
        NomeProd = new javax.swing.JLabel();
        CampoQuantidade = new javax.swing.JTextField();
        Quantidade = new javax.swing.JLabel();
        Preco = new javax.swing.JLabel();
        CampoPreco = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        CampoAddQuantidade = new javax.swing.JTextField();
        Alterar = new javax.swing.JButton();
        Deletar = new javax.swing.JButton();
        AddQuantidade = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estoque");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        NomedoProduto.setText("Nome do Produto");

        BotaoPesquisar.setText("Pesquisar");
        BotaoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoPesquisarActionPerformed(evt);
            }
        });

        Produto.setText("Produto");

        BotaoSelecionar.setText("Selecionar");
        BotaoSelecionar.setToolTipText("");
        BotaoSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSelecionarActionPerformed(evt);
            }
        });

        NomeProd.setText("Nome");

        Quantidade.setText("Quantidade Atual");

        Preco.setText("Preço");

        CampoPreco.setToolTipText("");

        jLabel1.setText("Adicionar Quantidade");

        Alterar.setText("Alterar");
        Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarActionPerformed(evt);
            }
        });

        Deletar.setText("Deletar");
        Deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletarActionPerformed(evt);
            }
        });

        AddQuantidade.setText("+");
        AddQuantidade.setActionCommand("");
        AddQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddQuantidadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Alterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Deletar)
                        .addGap(4, 4, 4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CampoAddQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(AddQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Produto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NomedoProduto)
                                    .addComponent(NomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Quantidade))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CampoPesqNome)
                                    .addComponent(ComboProduto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(CampoQuantidade)
                                                .addGap(62, 62, 62))
                                            .addComponent(CampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(143, 143, 143)
                                                .addComponent(Preco, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(CampoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BotaoPesquisar)
                                    .addComponent(BotaoSelecionar))))
                        .addGap(2, 2, 2))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomedoProduto)
                    .addComponent(CampoPesqNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoPesquisar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Produto)
                    .addComponent(BotaoSelecionar))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomeProd))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Quantidade)
                    .addComponent(Preco)
                    .addComponent(CampoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CampoAddQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Alterar)
                    .addComponent(Deletar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        telaanterior.setEnabled(true);
    }//GEN-LAST:event_formWindowClosed

    private void BotaoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoPesquisarActionPerformed
        // TODO add your handling code here:
         String pesquisar = this.CampoPesqNome.getText();
         ProdutoController pcontroller = new ProdutoController();
         List<Produto> lista = pcontroller.listar(pesquisar);
         ComboProduto.removeAllItems();
      
         for(int i=0;i<lista.size();i++){
             System.out.println("Entrou no for");
             System.out.println(lista.get(i));
             ComboProduto.addItem(lista.get(i).getNome());
         }
    }//GEN-LAST:event_BotaoPesquisarActionPerformed

    private void BotaoSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSelecionarActionPerformed
        // TODO add your handling code here:
        String select = ComboProduto.getSelectedItem().toString();
        ProdutoController pcontroller = new ProdutoController();
        Produto prod = new Produto();
        try {
            prod = pcontroller.consultar(select);
            CampoNome.setText(""+prod.getNome());
            CampoQuantidade.setText(""+prod.getQuantidade());
            CampoPreco.setText(""+prod.getPreco());
         
        } catch (UsuarioInexistenteException ex) {
           JOptionPane.showMessageDialog(rootPane, ex);
        }
        
    }//GEN-LAST:event_BotaoSelecionarActionPerformed

    private void AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarActionPerformed
        // TODO add your handling code here:
        String nome = CampoNome.getText();
        int quant = Integer.parseInt(CampoQuantidade.getText());
        double preco = Double.parseDouble(CampoPreco.getText());
        
    
        Produto produto = new Produto(nome,quant,preco);
        ProdutoController pcontroller = new ProdutoController();
        
        try{
            pcontroller.atualizar(produto);
        }catch(ErroInternoException e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_AlterarActionPerformed

    private void AddQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddQuantidadeActionPerformed
        // TODO add your handling code here:
        String nome = CampoNome.getText();
        double preco = Double.parseDouble(CampoPreco.getText());
        int quant = Integer.parseInt(CampoQuantidade.getText());
        int addquant = Integer.parseInt(CampoAddQuantidade.getText());
        int total = quant + addquant;
        this.CampoQuantidade.setText(""+total);
        
        Produto produto = new Produto(nome,total,preco);
        ProdutoController pcontroller = new ProdutoController();
        
        try{
            pcontroller.atualizar(produto);
        }catch(ErroInternoException e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_AddQuantidadeActionPerformed

    private void DeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletarActionPerformed
        // TODO add your handling code here:
         String nome = CampoNome.getText();
         ProdutoController pcontroller = new ProdutoController();
        try {
            JOptionPane.showMessageDialog(rootPane, JOptionPane.CANCEL_OPTION);
            pcontroller.deletar(nome);
        }catch (ErroInternoException ex) {
           JOptionPane.showMessageDialog(rootPane, ex);
        }catch(UsuarioInexistenteException e){
            
        }
        
    }//GEN-LAST:event_DeletarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEstoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddQuantidade;
    private javax.swing.JButton Alterar;
    private javax.swing.JButton BotaoPesquisar;
    private javax.swing.JButton BotaoSelecionar;
    private javax.swing.JTextField CampoAddQuantidade;
    private javax.swing.JTextField CampoNome;
    private javax.swing.JTextField CampoPesqNome;
    private javax.swing.JTextField CampoPreco;
    private javax.swing.JTextField CampoQuantidade;
    private javax.swing.JComboBox ComboProduto;
    private javax.swing.JButton Deletar;
    private javax.swing.JLabel NomeProd;
    private javax.swing.JLabel NomedoProduto;
    private javax.swing.JLabel Preco;
    private javax.swing.JLabel Produto;
    private javax.swing.JLabel Quantidade;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
