/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bonitoprint.telas;

import br.com.bonitoprint.controller.AdministradorController;
import br.com.bonitoprint.entidades.Administrador;
import br.com.bonitoprint.execao.CampoObrigatorioException;
import br.com.bonitoprint.execao.ErroInternoException;
import br.com.bonitoprint.execao.UsuarioExistenteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Vinicius
 */
public class TelaCadastroAdministrador extends javax.swing.JFrame {
    private TelaPrincipal telaanterior;
    /**
     * Creates new form TelaCadastroAdministrador
     */
    private TelaCadastroAdministrador() {
        initComponents();
    }
    public TelaCadastroAdministrador(TelaPrincipal telaanterior){
        this();
        this.telaanterior=telaanterior;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        NomeCadastroAdm = new javax.swing.JLabel();
        CampoNome = new javax.swing.JTextField();
        EmailAdm = new javax.swing.JLabel();
        CampoEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        CampoSenha = new javax.swing.JPasswordField();
        ConfirmaSenha = new javax.swing.JLabel();
        CampoConfirmaSenha = new javax.swing.JPasswordField();
        BotaoCadAdmSalvar = new javax.swing.JButton();
        BotaoCadAdmLimpar = new javax.swing.JButton();
        obrigatorio1 = new javax.swing.JLabel();
        obrigatorio2 = new javax.swing.JLabel();
        obrigatorio3 = new javax.swing.JLabel();
        obrigatorio4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Administrador");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        NomeCadastroAdm.setText("Nome");

        EmailAdm.setText("Email");

        jLabel1.setText("Senha");

        CampoSenha.setToolTipText("");

        ConfirmaSenha.setText("Confirmar a Senha");

        CampoConfirmaSenha.setToolTipText("");

        BotaoCadAdmSalvar.setText("Salvar");
        BotaoCadAdmSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadAdmSalvarActionPerformed(evt);
            }
        });

        BotaoCadAdmLimpar.setText("Limpar");
        BotaoCadAdmLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadAdmLimparActionPerformed(evt);
            }
        });

        obrigatorio1.setText("*");

        obrigatorio2.setText("*");

        obrigatorio3.setText("*");

        obrigatorio4.setText("*");

        jLabel6.setText("*Campos Obrigatorios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(ConfirmaSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoConfirmaSenha))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EmailAdm)
                                    .addComponent(jLabel1))
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CampoEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(CampoSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BotaoCadAdmSalvar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BotaoCadAdmLimpar))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(NomeCadastroAdm)
                                        .addGap(19, 19, 19)
                                        .addComponent(CampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(obrigatorio1)
                    .addComponent(obrigatorio2)
                    .addComponent(obrigatorio3)
                    .addComponent(obrigatorio4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeCadastroAdm)
                    .addComponent(CampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(obrigatorio1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailAdm)
                    .addComponent(CampoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(obrigatorio2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CampoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(obrigatorio3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmaSenha)
                    .addComponent(CampoConfirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(obrigatorio4))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoCadAdmSalvar)
                    .addComponent(BotaoCadAdmLimpar)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoCadAdmSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadAdmSalvarActionPerformed
        // TODO add your handling code here:
       
        String nome = CampoNome.getText();
        String email = CampoEmail.getText();
        String senha = String.valueOf(CampoSenha.getPassword());
        String senha2 = String.valueOf(CampoConfirmaSenha.getPassword());
               
        Administrador adm = new Administrador(nome,email,senha,senha2);
        
        AdministradorController admcontroller = new AdministradorController();
        
        try{
            if(senha.equals(senha2)){
                admcontroller.adicionar(adm);
                JOptionPane.showMessageDialog(rootPane,"Administrador Cadastrado com Sucesso", "Cadastro de Usuario", JOptionPane.INFORMATION_MESSAGE);      
                CampoNome.setText("");
                CampoEmail.setText("");
                CampoSenha.setText("");
                CampoConfirmaSenha.setText("");
            }else{
            JOptionPane.showMessageDialog(rootPane,"Senhas não Conferem", "Login", JOptionPane.ERROR_MESSAGE); 
            }
            }catch(UsuarioExistenteException e){
              JOptionPane.showMessageDialog(rootPane, e.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
            } catch (ErroInternoException ex) {
             JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
           }catch(CampoObrigatorioException cx){
             JOptionPane.showMessageDialog(rootPane, cx.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);  
           }
        
    }//GEN-LAST:event_BotaoCadAdmSalvarActionPerformed

    private void BotaoCadAdmLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadAdmLimparActionPerformed
        // TODO add your handling code here:
        
        CampoNome.setText("");
        CampoEmail.setText("");
        CampoSenha.setText("");
        CampoConfirmaSenha.setText("");
        
    }//GEN-LAST:event_BotaoCadAdmLimparActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
         telaanterior.setEnabled(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCadAdmLimpar;
    private javax.swing.JButton BotaoCadAdmSalvar;
    private javax.swing.JPasswordField CampoConfirmaSenha;
    private javax.swing.JTextField CampoEmail;
    private javax.swing.JTextField CampoNome;
    private javax.swing.JPasswordField CampoSenha;
    private javax.swing.JLabel ConfirmaSenha;
    private javax.swing.JLabel EmailAdm;
    private javax.swing.JLabel NomeCadastroAdm;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel obrigatorio1;
    private javax.swing.JLabel obrigatorio2;
    private javax.swing.JLabel obrigatorio3;
    private javax.swing.JLabel obrigatorio4;
    // End of variables declaration//GEN-END:variables
}
