/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bonitoprint.telas;

import br.com.bonitoprint.controller.ClienteController;
import br.com.bonitoprint.entidades.Cliente;
import br.com.bonitoprint.execao.CampoObrigatorioException;
import br.com.bonitoprint.execao.ErroInternoException;
import br.com.bonitoprint.execao.UsuarioExistenteException;
import javax.swing.JOptionPane;

/**
 *
 * @author Vinicius
 */
public class TelaCadastroCliente extends javax.swing.JFrame {
    private TelaPrincipal telaanterior;
    /**
     * Creates new form TelaCadastro
     */
    private TelaCadastroCliente() {
        initComponents();
    }
    public TelaCadastroCliente(TelaPrincipal telaanterior){
        this();
        this.telaanterior=telaanterior;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ClienteNome = new javax.swing.JLabel();
        CampoClienteNome = new javax.swing.JTextField();
        ClienteCpf = new javax.swing.JLabel();
        CampoClienteCpf = new javax.swing.JTextField();
        ClienteEmail = new javax.swing.JLabel();
        CampoClienteEmail = new javax.swing.JTextField();
        ClienteRua = new javax.swing.JLabel();
        CampoClienteRua = new javax.swing.JTextField();
        ClienteComplemento = new javax.swing.JLabel();
        CampoClienteComplemento = new javax.swing.JTextField();
        ClienteBairro = new javax.swing.JLabel();
        CampoClienteBairro = new javax.swing.JTextField();
        Cidade = new javax.swing.JLabel();
        CampoClienteCidade = new javax.swing.JTextField();
        BotaoSalvarCliente = new javax.swing.JButton();
        BotaoLimparCliente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        CampoNumero = new javax.swing.JTextField();
        CampoEstado = new javax.swing.JTextField();
        Estado = new javax.swing.JLabel();
        Tel1 = new javax.swing.JLabel();
        CampoTel1 = new javax.swing.JTextField();
        obrigatorio = new javax.swing.JLabel();
        obrigatorio1 = new javax.swing.JLabel();
        obrigatorio2 = new javax.swing.JLabel();
        Tel2 = new javax.swing.JLabel();
        CampoTel2 = new javax.swing.JTextField();
        obrigatorio3 = new javax.swing.JLabel();
        obrigatorio5 = new javax.swing.JLabel();
        obrigatroio4 = new javax.swing.JLabel();
        obrigatorio6 = new javax.swing.JLabel();
        obrigatorio7 = new javax.swing.JLabel();
        obrigatorio8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro do Cliente");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        ClienteNome.setText("Nome");

        ClienteCpf.setText("Cpf");

        ClienteEmail.setText("Email");

        ClienteRua.setText("Rua");

        ClienteComplemento.setText("Complemento");

        ClienteBairro.setText("Bairro");

        Cidade.setText("Cidade");

        BotaoSalvarCliente.setText("Salvar");
        BotaoSalvarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSalvarClienteActionPerformed(evt);
            }
        });

        BotaoLimparCliente.setText("Limpar");
        BotaoLimparCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLimparClienteActionPerformed(evt);
            }
        });

        jLabel1.setText("nº");

        Estado.setText("Estado");

        Tel1.setText("Tel 1 ");

        obrigatorio.setText("*");

        obrigatorio1.setText("* Campos Obrigatorios");

        obrigatorio2.setText("*");

        Tel2.setText("Tel 2");

        obrigatorio3.setText("*");

        obrigatorio5.setText("*");

        obrigatroio4.setText("*");

        obrigatorio6.setText("*");

        obrigatorio7.setText("*");

        obrigatorio8.setText("*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Estado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CampoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(obrigatorio7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Cidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoClienteCidade))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ClienteBairro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CampoClienteBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(obrigatorio6)
                    .addComponent(obrigatorio5))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(obrigatorio1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotaoSalvarCliente)
                .addGap(18, 18, 18)
                .addComponent(BotaoLimparCliente)
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ClienteNome, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ClienteRua, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(ClienteEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ClienteCpf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CampoClienteEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(CampoClienteRua, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(3, 3, 3)
                                                .addComponent(obrigatroio4, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(CampoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(CampoClienteNome, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(obrigatorio2))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(CampoClienteCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(obrigatorio))))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ClienteComplemento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoClienteComplemento)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(obrigatorio3, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Tel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CampoTel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(obrigatorio8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Tel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoTel2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClienteNome, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoClienteNome, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(obrigatorio2))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClienteCpf)
                    .addComponent(CampoClienteCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(obrigatorio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClienteEmail)
                    .addComponent(CampoClienteEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClienteRua)
                    .addComponent(CampoClienteRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(CampoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(obrigatorio3)
                    .addComponent(obrigatroio4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClienteComplemento)
                    .addComponent(CampoClienteComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClienteBairro)
                    .addComponent(CampoClienteBairro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(obrigatorio5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cidade)
                    .addComponent(CampoClienteCidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(obrigatorio6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Estado)
                    .addComponent(obrigatorio7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tel1)
                    .addComponent(CampoTel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tel2)
                    .addComponent(CampoTel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(obrigatorio8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(obrigatorio1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotaoSalvarCliente)
                            .addComponent(BotaoLimparCliente))
                        .addGap(20, 20, 20))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoSalvarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSalvarClienteActionPerformed
        // TODO add your handling code here:
        String nome = CampoClienteNome.getText();
        String email = CampoClienteEmail.getText();
        String cpf = CampoClienteCpf.getText();
        String rua = CampoClienteRua.getText();
        String complemento = CampoClienteComplemento.getText();
        String bairro = CampoClienteBairro.getText();
        String cidade = CampoClienteCidade.getText();
        String estado = CampoEstado.getText();
        String tel1= CampoTel1.getText();
        String tel2 = CampoTel2.getText();
        String num = CampoNumero.getText();
        if(num.length()<=0){
           JOptionPane.showMessageDialog(rootPane,"Campo Obrigatorio", "ERRO", JOptionPane.ERROR_MESSAGE);
        }else{
        int numero = Integer.parseInt(CampoNumero.getText());
        Cliente cliente = new Cliente(tel1,tel2,nome,email,cpf,rua,numero,complemento,bairro,cidade,estado);
       
        ClienteController c = new ClienteController();
        try{
            c.adicionar(cliente);
            JOptionPane.showMessageDialog(rootPane,"Cliente Cadastrado com Sucesso", "Cadastro de Usuario", JOptionPane.INFORMATION_MESSAGE);
            CampoClienteNome.setText("");
            CampoClienteEmail.setText("");
            CampoClienteCpf.setText("");
            CampoClienteRua.setText("");
            CampoNumero.setText("");
            CampoClienteComplemento.setText("");
            CampoClienteBairro.setText("");
            CampoClienteCidade.setText("");
            CampoEstado.setText("");
            CampoTel1.setText("");
            CampoTel2.setText("");
        }catch(UsuarioExistenteException e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
        }    
        catch(ErroInternoException erro){
             JOptionPane.showMessageDialog(rootPane, erro.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
        }catch(CampoObrigatorioException ex){
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        } 
    }//GEN-LAST:event_BotaoSalvarClienteActionPerformed

    private void BotaoLimparClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoLimparClienteActionPerformed
        // TODO add your handling code here:
        
        CampoClienteNome.setText("");
        CampoClienteEmail.setText("");
        CampoClienteCpf.setText("");
        CampoClienteRua.setText("");
        CampoNumero.setText("");
        CampoClienteComplemento.setText("");
        CampoClienteBairro.setText("");
        CampoClienteCidade.setText("");
        CampoEstado.setText("");
        CampoTel1.setText("");
        CampoTel2.setText("");
    }//GEN-LAST:event_BotaoLimparClienteActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        telaanterior.setEnabled(true);
        
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoLimparCliente;
    private javax.swing.JButton BotaoSalvarCliente;
    private javax.swing.JTextField CampoClienteBairro;
    private javax.swing.JTextField CampoClienteCidade;
    private javax.swing.JTextField CampoClienteComplemento;
    private javax.swing.JTextField CampoClienteCpf;
    private javax.swing.JTextField CampoClienteEmail;
    private javax.swing.JTextField CampoClienteNome;
    private javax.swing.JTextField CampoClienteRua;
    private javax.swing.JTextField CampoEstado;
    private javax.swing.JTextField CampoNumero;
    private javax.swing.JTextField CampoTel1;
    private javax.swing.JTextField CampoTel2;
    private javax.swing.JLabel Cidade;
    private javax.swing.JLabel ClienteBairro;
    private javax.swing.JLabel ClienteComplemento;
    private javax.swing.JLabel ClienteCpf;
    private javax.swing.JLabel ClienteEmail;
    private javax.swing.JLabel ClienteNome;
    private javax.swing.JLabel ClienteRua;
    private javax.swing.JLabel Estado;
    private javax.swing.JLabel Tel1;
    private javax.swing.JLabel Tel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel obrigatorio;
    private javax.swing.JLabel obrigatorio1;
    private javax.swing.JLabel obrigatorio2;
    private javax.swing.JLabel obrigatorio3;
    private javax.swing.JLabel obrigatorio5;
    private javax.swing.JLabel obrigatorio6;
    private javax.swing.JLabel obrigatorio7;
    private javax.swing.JLabel obrigatorio8;
    private javax.swing.JLabel obrigatroio4;
    // End of variables declaration//GEN-END:variables
}
