/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bonitoprint.telas;

import br.com.bonitoprint.controller.AdministradorController;
import br.com.bonitoprint.entidades.Administrador;
import br.com.bonitoprint.execao.UsuarioInexistenteException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Vinicius
 */
public class TelaPrincipal extends javax.swing.JFrame {
   
    
    /**
     * Creates new form Main
     */
    public TelaPrincipal() {
        initComponents();
        BarradeMenus.setVisible(false);
        NomeAdm.setVisible(false);
        Desconectar.setVisible(false);
        PainelLogin.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        PainelLogin = new javax.swing.JPanel();
        SenhaNome = new javax.swing.JLabel();
        Senha = new javax.swing.JLabel();
        CampoEmailSenha = new javax.swing.JTextField();
        BotaoEntar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BotaoCancelar = new javax.swing.JButton();
        CampoSenha = new javax.swing.JPasswordField();
        JData = new javax.swing.JLabel();
        JHora = new javax.swing.JLabel();
        NomeAdm = new javax.swing.JLabel();
        CampoNomeAdm = new javax.swing.JLabel();
        Desconectar = new javax.swing.JButton();
        BarradeMenus = new javax.swing.JMenuBar();
        Cadastrar = new javax.swing.JMenu();
        CadastroAdministrador = new javax.swing.JMenuItem();
        CadastrarCliente = new javax.swing.JMenuItem();
        CadastrarFornecedor = new javax.swing.JMenuItem();
        CadastrarProduto = new javax.swing.JMenuItem();
        CadastrarServico = new javax.swing.JMenuItem();
        Status = new javax.swing.JMenuItem();
        Consultar = new javax.swing.JMenu();
        Estoque = new javax.swing.JMenu();
        EntradaEstoque = new javax.swing.JMenuItem();
        Vendas = new javax.swing.JMenu();
        VendasProdutos = new javax.swing.JMenuItem();
        VendasServico = new javax.swing.JMenuItem();
        Relatorios = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        popupMenu1.setLabel("popupMenu1");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BonitoPrint");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        PainelLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), java.awt.Color.black, null, null));
        PainelLogin.setName("Login Administrador"); // NOI18N

        SenhaNome.setText("Email");

        Senha.setText("Senha");

        BotaoEntar.setText("Entrar");
        BotaoEntar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEntarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Login do Administardor");

        BotaoCancelar.setText("Cancelar");
        BotaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelLoginLayout = new javax.swing.GroupLayout(PainelLogin);
        PainelLogin.setLayout(PainelLoginLayout);
        PainelLoginLayout.setHorizontalGroup(
            PainelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLoginLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(PainelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Senha)
                    .addComponent(SenhaNome))
                .addGap(18, 18, 18)
                .addGroup(PainelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CampoEmailSenha)
                    .addComponent(CampoSenha))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelLoginLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addGroup(PainelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelLoginLayout.createSequentialGroup()
                        .addComponent(BotaoEntar)
                        .addGap(18, 18, 18)
                        .addComponent(BotaoCancelar)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelLoginLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
        );
        PainelLoginLayout.setVerticalGroup(
            PainelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(PainelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SenhaNome)
                    .addComponent(CampoEmailSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Senha)
                    .addComponent(CampoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(PainelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoEntar)
                    .addComponent(BotaoCancelar))
                .addGap(13, 13, 13))
        );

        JData.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        JHora.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        NomeAdm.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        NomeAdm.setText("Administrador:");

        CampoNomeAdm.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        Desconectar.setText("Desconectar");
        Desconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DesconectarActionPerformed(evt);
            }
        });

        Cadastrar.setText("Cadastrar");

        CadastroAdministrador.setText("Administrador");
        CadastroAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroAdministradorActionPerformed(evt);
            }
        });
        Cadastrar.add(CadastroAdministrador);

        CadastrarCliente.setText("Cliente");
        CadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarClienteActionPerformed(evt);
            }
        });
        Cadastrar.add(CadastrarCliente);

        CadastrarFornecedor.setText("Fornecedor");
        CadastrarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarFornecedorActionPerformed(evt);
            }
        });
        Cadastrar.add(CadastrarFornecedor);

        CadastrarProduto.setText("Produto");
        CadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarProdutoActionPerformed(evt);
            }
        });
        Cadastrar.add(CadastrarProduto);

        CadastrarServico.setText("Serviços");
        CadastrarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarServicoActionPerformed(evt);
            }
        });
        Cadastrar.add(CadastrarServico);

        Status.setText("Status");
        Status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusActionPerformed(evt);
            }
        });
        Cadastrar.add(Status);

        BarradeMenus.add(Cadastrar);

        Consultar.setText("Consultar");
        BarradeMenus.add(Consultar);

        Estoque.setText("Estoque");

        EntradaEstoque.setText("Entrada de Produtos");
        EntradaEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaEstoqueActionPerformed(evt);
            }
        });
        Estoque.add(EntradaEstoque);

        BarradeMenus.add(Estoque);

        Vendas.setText("Vender");

        VendasProdutos.setText("Produto");
        Vendas.add(VendasProdutos);

        VendasServico.setText("Serviços");
        Vendas.add(VendasServico);

        BarradeMenus.add(Vendas);

        Relatorios.setText("Relatórios");
        BarradeMenus.add(Relatorios);

        jMenu2.setText("jMenu2");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        BarradeMenus.add(jMenu2);

        setJMenuBar(BarradeMenus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JData, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JHora, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(NomeAdm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoNomeAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Desconectar)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(PainelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CampoNomeAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Desconectar))
                    .addComponent(NomeAdm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(PainelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JHora, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(JData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void CadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarClienteActionPerformed
        // TODO add your handling code here:
        this.setEnabled(false);
        new TelaCadastroCliente(this).setVisible(true);
    }//GEN-LAST:event_CadastrarClienteActionPerformed

    private void CadastroAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroAdministradorActionPerformed
        // TODO add your handling code here:
        this.setEnabled(false);
        new TelaCadastroAdministrador(this).setVisible(true);
    }//GEN-LAST:event_CadastroAdministradorActionPerformed

    private void CadastrarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarFornecedorActionPerformed
        // TODO add your handling code here:
        this.setEnabled(false);
        new TelaCadastroFornecedor(this).setVisible(true);
    }//GEN-LAST:event_CadastrarFornecedorActionPerformed

    private void CadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarProdutoActionPerformed
        // TODO add your handling code here:
        this.setEnabled(false);
        new TelaCadastroProduto(this).setVisible(true);
    }//GEN-LAST:event_CadastrarProdutoActionPerformed

    private void CadastrarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarServicoActionPerformed
        // TODO add your handling code here:
        this.setEnabled(false);
        new TelaCadastroServico(this).setVisible(true);
    }//GEN-LAST:event_CadastrarServicoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        LocalDate hoje = LocalDate.now();
        
        Date datasistema = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        JData.setText(formato.format(datasistema));
        
        //hora
        Timer timer = new Timer(1000, new hora());
        timer.start();
    }//GEN-LAST:event_formWindowOpened

    private void StatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusActionPerformed
        // TODO add your handling code here:
        this.setEnabled(false);
        new TelaCadastroStatus(this).setVisible(true);
        
    }//GEN-LAST:event_StatusActionPerformed

    private void BotaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCancelarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BotaoCancelarActionPerformed

    private void BotaoEntarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEntarActionPerformed
        // TODO add your handling code here:
        String email = CampoEmailSenha.getText();
        String senha = String.valueOf(CampoSenha.getPassword());
        Administrador adm = new Administrador();
        AdministradorController admcontroller = new AdministradorController();
        try{
         
          adm = admcontroller.consultar(email);
           if(adm.getSenha().equals(senha)){
            this.PainelLogin.setVisible(false);
            this.CampoNomeAdm.setVisible(true);
            this.CampoNomeAdm.setText(adm.getNome());
            this.NomeAdm.setVisible(true);
            this.Desconectar.setVisible(true);
            this.BarradeMenus.setVisible(true);
           }else{
               JOptionPane.showMessageDialog(rootPane,"Senha Incorreta","ERRO", JOptionPane.ERROR_MESSAGE);
           }
        }catch(UsuarioInexistenteException ex){
               JOptionPane.showMessageDialog(rootPane,"Usuario Inexistente","ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotaoEntarActionPerformed

    private void DesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesconectarActionPerformed
        // TODO add your handling code here
        
        this.CampoNomeAdm.setVisible(false);
        this.NomeAdm.setVisible(false);
        PainelLogin.setVisible(true);
        this.Desconectar.setVisible(false);
        BarradeMenus.setVisible(false);
        CampoNomeAdm.setText("");
        CampoSenha.setText("");
    }//GEN-LAST:event_DesconectarActionPerformed

    private void EntradaEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaEstoqueActionPerformed
        // TODO add your handling code here:
        this.setEnabled(false);
        new TelaEstoque(this).setVisible(true);
    }//GEN-LAST:event_EntradaEstoqueActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        this.setEnabled(false);
        new TelaEstoque(this).setVisible(true);
    }//GEN-LAST:event_jMenu2ActionPerformed
    
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new TelaPrincipal().setVisible(true);
            }
        }
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarradeMenus;
    private javax.swing.JButton BotaoCancelar;
    private javax.swing.JButton BotaoEntar;
    private javax.swing.JMenu Cadastrar;
    private javax.swing.JMenuItem CadastrarCliente;
    private javax.swing.JMenuItem CadastrarFornecedor;
    private javax.swing.JMenuItem CadastrarProduto;
    private javax.swing.JMenuItem CadastrarServico;
    private javax.swing.JMenuItem CadastroAdministrador;
    private javax.swing.JTextField CampoEmailSenha;
    private javax.swing.JLabel CampoNomeAdm;
    private javax.swing.JPasswordField CampoSenha;
    private javax.swing.JMenu Consultar;
    private javax.swing.JButton Desconectar;
    private javax.swing.JMenuItem EntradaEstoque;
    private javax.swing.JMenu Estoque;
    private javax.swing.JLabel JData;
    private javax.swing.JLabel JHora;
    private javax.swing.JLabel NomeAdm;
    private javax.swing.JPanel PainelLogin;
    private javax.swing.JMenu Relatorios;
    private javax.swing.JLabel Senha;
    private javax.swing.JLabel SenhaNome;
    private javax.swing.JMenuItem Status;
    private javax.swing.JMenu Vendas;
    private javax.swing.JMenuItem VendasProdutos;
    private javax.swing.JMenuItem VendasServico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables

class hora implements ActionListener {
    @Override
    public void actionPerformed( ActionEvent e){
        Calendar now = Calendar.getInstance();
        JHora.setText(String.format("%1$tH:%1$tM:%1$tS", now));
    }
}
}
